load("//language-tools/lexer:lexer_builder.bzl", "lexer_builder")

package(
    default_visibility = ["//language-tools:internal"],
)

lexer_builder(
    name = "production_lexer",
    comments = "comments.txt",
    keywords = "keywords.txt",
    strings = "strings.txt",
    symbols = "symbols.txt",
)
